import type { Metadata } from 'next';
import './globals.css';
import AuthProvider from '@/context/auth';
import Header from '@/components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <AuthProvider>
          <Header />
          <div className="w-screen">{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
